# Um neurônio

In [9]:
entradas = [1, 2, 3]

In [10]:
# "Chutes" iniciais
pesos = [0.2, 0.8, -0.5]
bias = 2

In [11]:
saida = (entradas[0]*pesos[0] + entradas[1]*pesos[1] + entradas[2]*pesos[2] + bias)
print(saida)

2.3


# Três neurônios

In [20]:
entradas = [1, 2, 3, 2.5]

In [17]:
pesos1 = [0.2, 0.8, -0.5, 1]
pesos2 = [0.5, -0.91, 0.26, -0.5]
pesos3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

In [19]:
saidas = [
        # Neurônio 1
        entradas[0]*pesos1[0] + entradas[1]*pesos1[1] + entradas[2]*pesos1[2] + entradas[3]*pesos1[3] + bias1,

        # Neurônio 2
        entradas[0]*pesos2[0] + entradas[1]*pesos2[1] + entradas[2]*pesos2[2] + entradas[3]*pesos2[3] + bias2,
        
        # Neurônio 3
        entradas[0]*pesos3[0] + entradas[1]*pesos3[1] + entradas[2]*pesos3[2] + entradas[3]*pesos3[3] + bias3
]

print(saidas)

[4.8, 1.21, 2.385]


# Rede Neural Feed-Forward

## Problema: 

Vamos treinar a rede neural de forma que ela possa prever o valor de saída correto quando fornecida com um novo conjunto de dados.

In [21]:
import numpy as np

Entrada: Matriz (4x3)

![Entrada](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/b065b929-ae87-446d-a042-b065d93bff9c/Screen_Shot_2021-08-30_at_12.00.30.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210830%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210830T231509Z&X-Amz-Expires=86400&X-Amz-Signature=f90860ce7b2d580c7041446c7184b85b2fe8f83fd68481e2090716a54d006dcb&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Screen%2520Shot%25202021-08-30%2520at%252012.00.30.png%22)

## Dados

In [24]:
treinamento_entrada = np.array([[0, 0, 1], 
                                [1, 1, 1], 
                                [1, 0, 1], 
                                [0, 1, 1]])

In [31]:
treinamento_resultado = np.array([[0, 1, 1, 0]]).T  # .T -> Calcula a transposta (por isso cria como matriz)

In [36]:
np.random.seed(seed=42)

## Pesos

In [52]:
pesos_sinapticos = 2 * np.random.random((3,1)) - 1
pesos_sinapticos

array([[ 0.32504457],
       [-0.37657785],
       [ 0.04013604]])

## Função de Ativação

Sigmoid :
$$\sigma(x) = \frac{1}{1+e^{-x}}$$



![Sigmoid](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/4a4981e4-bcf5-48b6-b4dc-19c44570207e/main-qimg-6b67bea3311c3429bfb34b6b1737fe0c.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210830%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210830T232544Z&X-Amz-Expires=86400&X-Amz-Signature=4f9c97fe4a8270e230c0fab8ebe9508911d980c4ca3ba13335de5c8e8c5af590&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22main-qimg-6b67bea3311c3429bfb34b6b1737fe0c.jpeg%22)

In [56]:
# Definindo a sigmoid
def sigmoid(x):
    return 1/(1 + np.exp(-x))

Derivada da sigmoid :
$$ \frac{d}{dx}\sigma(x) = x \times (1-x)$$

In [57]:
def sigmoid_derivate(x):
    return x * (1 - x)

## Treinamento

![ModeloDeRede](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/20bc00ef-abba-48a4-b40e-be963dede437/Screen_Shot_2021-08-30_at_11.16.16.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210830%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210830T233247Z&X-Amz-Expires=86400&X-Amz-Signature=138a189e630e4adfe8812cb522e1d8beedd3224b0dcf80d6b924283731087b28&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Screen%2520Shot%25202021-08-30%2520at%252011.16.16.png%22)

In [68]:
for i in range(10000):
    input_layer = treinamento_entrada
    output = sigmoid(np.dot(input_layer, pesos_sinapticos))
    
    erro = treinamento_resultado - output
    ajuste = erro * sigmoid_derivate(output)

    pesos_sinapticos += np.dot(input_layer.T, ajuste)


In [70]:
# Pesos encontrados
print(pesos_sinapticos)

array([[10.79215448],
       [-0.20602524],
       [-5.19076595]])

In [73]:
# Valores finais encontrados
print(output)

# = [0, 1, 1, 0]

[[0.00553701]
 [0.99548285]
 [0.99632079]
 [0.00451073]]
