# Data Preprocessing 

## Importing the libraries

In [ ]:
import numpy as np                # Work with arrays, machine learning models use arrays as inputs
import matplotlib.pyplot as plt   # Plotting
import pandas as pd               # Import dataset and create the matrix of features and dependent variable vector

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv') 
X = dataset.iloc[:, :-1].values  # Matrix of features (Independent variable), x: numpy.ndarray
y = dataset.iloc[:, -1].values   # Dependent variable vector (what you want to predict), y: numpy.ndarray


# iloc[rows, columns]
# .values -> pandas.Series to numpy.ndarray

In [ ]:
display(dataset)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

1. Ignore the missing data and just delete it (Depents of the % of the missing data)
2. Replace the missing data by the {average, median, mean, most frequenty value} of all values of the same column

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')   # Create a Object of SimpleImputer class
imputer.fit(X[:, 1:3])                     # .fit expects numerical columns, so we pass only 'Age' and 'Salary' columns, [1:3]
X[:, 1:3] = imputer.transform(X[:, 1:3])   # .transform expects the columns of X where we want to replace the missing data
                                           # .transform returns a new numpy array with the new data, X[:, 1:3] = .transform


# missing_values=np.nan -> Defining np.nan as the missing values
# strategy='mean'       -> Substite np.nan by the strategy (mean)
# .fit                  -> connect the 'imputer' to the matrix of features
# .transform            -> actually will make the replacement

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Enconding categorical data



### Enconding the Independent Variable (One-hot Encoder)

We can't just say "France = 1", "Spain = 2", "Germany = 3". Our machine learning model will understand that it has an numerical order and worst, this order matters. WE DON'T WANT IT !!!


**One-hot Encoder:**

Turn this Country column into three columns, because we have three different classes on Country column, and it will create a **binary vector** for each of this coutries. For example: 

France = [1 0 0] 

Spain = [0 1 0]

Germany = [0 0 1]

And now, there is no numerical order involved

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')   # Create a Object of ColumnTransformer class
X = np.array(ct.fit_transform(X))   # .fit_transform returns a new object


# transformers=[(kind of transformation, what kind of enconding(), [indexs of the columns we want to enconde[])]
# remainder='passthrough' -> we want to keep the columns that we are not encoding
# np.array() -> to force the output to be a numpy array

In [ ]:
print(X)   # Dummie Variables

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Enconding the Dependent Variable

On Purchased column, we will turn 'Yes' into '1' and 'No' into '0'

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()   # Create a Object of LabelEncoder class
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

We do the Feature Scaling to prevents that one feature became for revalent than other. Feature Scaling = makes all features have the same "weight".


- AFTER splitting the dataset. 

That's because we don't want to show Test set to out machine learning model, it is suppose to be new data, new observations to ML model.

- Do not apply to our Dummie Variable, it is already scalled

- We don't need to apply Feature Scaling to all ML models.



### Standardisation

$$ x_{stand} = \frac{x-mean(x)}{sd(x)} $$

Where, $sd$ is the Standard deviation

Results: between -3 and +3

It will work all the time, no restriction.

### Normalisation

$$ x_{norm} = \frac{x-min(x)}{max(x) - min(x)} $$

Results: between 0 and +1

It it used when you have a Normal Distribution to most your features

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()   # Create a Object of StandardScaler class

X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])   # Only apply to 'Age' and 'Salary'
X_test[:, 3:] = sc.fit_transform(X_test[:, 3:])     # Only apply to 'Age' and 'Salary'

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
